TrajectoryPlannerROS:
    max_vel_x: 0.42
    min_vel_x: -0.42
    max_vel_theta: 1.7
    min_in_place_vel_theta: 1.7
    escape_vel: -0.42
    acc_lim_theta: 8
    acc_lim_x: 0.8
  
    holonomic_robot: false
