local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0 # actually exactly 5.0Hz, see https://github.com/ros-planning/navigation/issues/383
  static_map: false
  rolling_window: true
  width: 1
  height: 1
  resolution: 0.05
  transform_tolerance: 0.5
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
