#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_telemetrix:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_sim:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_control:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_msgs:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_description:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_bringup:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_perception:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_nav:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_hri:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_control:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_bringup:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/apriltag_ros:/opt/ros/noetic:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/apriltag'
export LD_LIBRARY_PATH='/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_telemetrix/lib:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_sim/lib:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_control/lib:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_msgs/lib:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_description/lib:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_perception/lib:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_nav/lib:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_hri/lib:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_control/lib:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_bringup/lib:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/apriltag_ros/lib:/opt/ros/noetic/lib:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/apriltag/lib'
export PATH='/opt/ros/noetic/bin:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/apriltag/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_telemetrix/lib/pkgconfig:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_sim/lib/pkgconfig:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_control/lib/pkgconfig:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_msgs/lib/pkgconfig:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_description/lib/pkgconfig:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_perception/lib/pkgconfig:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_nav/lib/pkgconfig:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_hri/lib/pkgconfig:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_control/lib/pkgconfig:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/bullproof_bringup/lib/pkgconfig:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/apriltag_ros/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/apriltag/lib/pkgconfig'
export ROSLISP_PACKAGE_DIRECTORIES="/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/devel_isolated/mirte_telemetrix/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_telemetrix:$ROS_PACKAGE_PATH"