set(_CATKIN_CURRENT_PACKAGE "bullproof_control")
set(bullproof_control_VERSION "0.0.1")
set(bullproof_control_MAINTAINER "Jelmer van der Saag <jelmer@todo.todo>")
set(bullproof_control_PACKAGE_FORMAT "2")
set(bullproof_control_BUILD_DEPENDS "geometry_msgs" "rospy")
set(bullproof_control_BUILD_EXPORT_DEPENDS "geometry_msgs" "rospy")
set(bullproof_control_BUILDTOOL_DEPENDS "catkin")
set(bullproof_control_BUILDTOOL_EXPORT_DEPENDS )
set(bullproof_control_EXEC_DEPENDS "geometry_msgs" "rospy")
set(bullproof_control_RUN_DEPENDS "geometry_msgs" "rospy")
set(bullproof_control_TEST_DEPENDS )
set(bullproof_control_DOC_DEPENDS )
set(bullproof_control_URL_WEBSITE "")
set(bullproof_control_URL_BUGTRACKER "")
set(bullproof_control_URL_REPOSITORY "")
set(bullproof_control_DEPRECATED "")