set(_CATKIN_CURRENT_PACKAGE "mirte_control")
set(mirte_control_VERSION "0.1.0")
set(mirte_control_MAINTAINER "Martin Klomp <m.klomp@tudelft.nl>")
set(mirte_control_PACKAGE_FORMAT "2")
set(mirte_control_BUILD_DEPENDS "roscpp" "std_msgs" "mirte_msgs" "controller_manager" "hardware_interface" "trajectory_msgs")
set(mirte_control_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(mirte_control_BUILDTOOL_DEPENDS "catkin")
set(mirte_control_BUILDTOOL_EXPORT_DEPENDS )
set(mirte_control_EXEC_DEPENDS "roscpp" "std_msgs" "mirte_msgs" "message_runtime" "controller_manager" "hardware_interface" "effort_controllers" "trajectory_msgs" "diff_drive_controller")
set(mirte_control_RUN_DEPENDS "roscpp" "std_msgs" "mirte_msgs" "message_runtime" "controller_manager" "hardware_interface" "effort_controllers" "trajectory_msgs" "diff_drive_controller")
set(mirte_control_TEST_DEPENDS )
set(mirte_control_DOC_DEPENDS )
set(mirte_control_URL_WEBSITE "")
set(mirte_control_URL_BUGTRACKER "")
set(mirte_control_URL_REPOSITORY "")
set(mirte_control_DEPRECATED "")