set(_CATKIN_CURRENT_PACKAGE "bullproof_nav")
set(bullproof_nav_VERSION "0.0.1")
set(bullproof_nav_MAINTAINER "jvandersaag <jvandersaag@todo.todo>")
set(bullproof_nav_PACKAGE_FORMAT "2")
set(bullproof_nav_BUILD_DEPENDS "move_base")
set(bullproof_nav_BUILD_EXPORT_DEPENDS "move_base")
set(bullproof_nav_BUILDTOOL_DEPENDS "catkin")
set(bullproof_nav_BUILDTOOL_EXPORT_DEPENDS )
set(bullproof_nav_EXEC_DEPENDS "move_base")
set(bullproof_nav_RUN_DEPENDS "move_base")
set(bullproof_nav_TEST_DEPENDS )
set(bullproof_nav_DOC_DEPENDS )
set(bullproof_nav_URL_WEBSITE "")
set(bullproof_nav_URL_BUGTRACKER "")
set(bullproof_nav_URL_REPOSITORY "")
set(bullproof_nav_DEPRECATED "")