# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/msg/Encoder.msg;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/msg/color.msg;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/msg/Intensity.msg;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/msg/IntensityDigital.msg;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/msg/Keypad.msg"
services_str = "/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/GetDistance.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/GetIntensity.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/GetIntensityDigital.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/GetEncoder.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/GetKeypad.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/SetPinMode.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/GetPinValue.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/SetPinValue.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/SetLEDValue.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/SetOLEDImage.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/SetServoAngle.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/get_virtual_color.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/get_barcode.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/SetMotorSpeed.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/Move.srv;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/srv/Turn.srv"
pkg_name = "mirte_msgs"
dependencies_str = "std_msgs;geometry_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "mirte_msgs;/home/tanyaspee/mdp/bullproof-tech/bullproof_ws/src/mirte-ros-packages/mirte_msgs/msg;std_msgs;/opt/ros/noetic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/noetic/share/geometry_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python3"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/noetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
