(cl:defpackage bullproof_nav-msg
  (:use )
  (:export
   "<NAVPOSE2DACTION>"
   "NAVPOSE2DACTION"
   "<NAVPOSE2DACTIONFEEDBACK>"
   "NAVPOSE2DACTIONFEEDBACK"
   "<NAVPOSE2DACTIONGOAL>"
   "NAVPOSE2DACTIONGOAL"
   "<NAVPOSE2DACTIONRESULT>"
   "NAVPOSE2DACTIONRESULT"
   "<NAVPOSE2DFEEDBACK>"
   "NAVPOSE2DFEEDBACK"
   "<NAVPOSE2DGOAL>"
   "NAVPOSE2DGOAL"
   "<NAVPOSE2DRESULT>"
   "NAVPOSE2DRESULT"
  ))

