; Auto-generated. Do not edit!


(cl:in-package bullproof_nav-msg)


;//! \htmlinclude NavPose2DFeedback.msg.html

(cl:defclass <NavPose2DFeedback> (roslisp-msg-protocol:ros-message)
  ((distance_left
    :reader distance_left
    :initarg :distance_left
    :type cl:float
    :initform 0.0))
)

(cl:defclass NavPose2DFeedback (<NavPose2DFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavPose2DFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavPose2DFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bullproof_nav-msg:<NavPose2DFeedback> is deprecated: use bullproof_nav-msg:NavPose2DFeedback instead.")))

(cl:ensure-generic-function 'distance_left-val :lambda-list '(m))
(cl:defmethod distance_left-val ((m <NavPose2DFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bullproof_nav-msg:distance_left-val is deprecated.  Use bullproof_nav-msg:distance_left instead.")
  (distance_left m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavPose2DFeedback>) ostream)
  "Serializes a message object of type '<NavPose2DFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'distance_left))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavPose2DFeedback>) istream)
  "Deserializes a message object of type '<NavPose2DFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distance_left) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavPose2DFeedback>)))
  "Returns string type for a message object of type '<NavPose2DFeedback>"
  "bullproof_nav/NavPose2DFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavPose2DFeedback)))
  "Returns string type for a message object of type 'NavPose2DFeedback"
  "bullproof_nav/NavPose2DFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavPose2DFeedback>)))
  "Returns md5sum for a message object of type '<NavPose2DFeedback>"
  "cee420620fc0275f177e13260e85fa34")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavPose2DFeedback)))
  "Returns md5sum for a message object of type 'NavPose2DFeedback"
  "cee420620fc0275f177e13260e85fa34")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavPose2DFeedback>)))
  "Returns full string definition for message of type '<NavPose2DFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 distance_left~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavPose2DFeedback)))
  "Returns full string definition for message of type 'NavPose2DFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 distance_left~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavPose2DFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavPose2DFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'NavPose2DFeedback
    (cl:cons ':distance_left (distance_left msg))
))
