; Auto-generated. Do not edit!


(cl:in-package bullproof_nav-msg)


;//! \htmlinclude NavPose2DGoal.msg.html

(cl:defclass <NavPose2DGoal> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type geometry_msgs-msg:Pose2D
    :initform (cl:make-instance 'geometry_msgs-msg:Pose2D)))
)

(cl:defclass NavPose2DGoal (<NavPose2DGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavPose2DGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavPose2DGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bullproof_nav-msg:<NavPose2DGoal> is deprecated: use bullproof_nav-msg:NavPose2DGoal instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <NavPose2DGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bullproof_nav-msg:pose-val is deprecated.  Use bullproof_nav-msg:pose instead.")
  (pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavPose2DGoal>) ostream)
  "Serializes a message object of type '<NavPose2DGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavPose2DGoal>) istream)
  "Deserializes a message object of type '<NavPose2DGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavPose2DGoal>)))
  "Returns string type for a message object of type '<NavPose2DGoal>"
  "bullproof_nav/NavPose2DGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavPose2DGoal)))
  "Returns string type for a message object of type 'NavPose2DGoal"
  "bullproof_nav/NavPose2DGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavPose2DGoal>)))
  "Returns md5sum for a message object of type '<NavPose2DGoal>"
  "271cb12677c4cd9bccbc642cd9258d1f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavPose2DGoal)))
  "Returns md5sum for a message object of type 'NavPose2DGoal"
  "271cb12677c4cd9bccbc642cd9258d1f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavPose2DGoal>)))
  "Returns full string definition for message of type '<NavPose2DGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Pose2D pose~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavPose2DGoal)))
  "Returns full string definition for message of type 'NavPose2DGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Pose2D pose~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavPose2DGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavPose2DGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'NavPose2DGoal
    (cl:cons ':pose (pose msg))
))
