; Auto-generated. Do not edit!


(cl:in-package bullproof_nav-msg)


;//! \htmlinclude NavPose2DResult.msg.html

(cl:defclass <NavPose2DResult> (roslisp-msg-protocol:ros-message)
  ((reached
    :reader reached
    :initarg :reached
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass NavPose2DResult (<NavPose2DResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavPose2DResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavPose2DResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bullproof_nav-msg:<NavPose2DResult> is deprecated: use bullproof_nav-msg:NavPose2DResult instead.")))

(cl:ensure-generic-function 'reached-val :lambda-list '(m))
(cl:defmethod reached-val ((m <NavPose2DResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bullproof_nav-msg:reached-val is deprecated.  Use bullproof_nav-msg:reached instead.")
  (reached m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavPose2DResult>) ostream)
  "Serializes a message object of type '<NavPose2DResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'reached) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavPose2DResult>) istream)
  "Deserializes a message object of type '<NavPose2DResult>"
    (cl:setf (cl:slot-value msg 'reached) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavPose2DResult>)))
  "Returns string type for a message object of type '<NavPose2DResult>"
  "bullproof_nav/NavPose2DResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavPose2DResult)))
  "Returns string type for a message object of type 'NavPose2DResult"
  "bullproof_nav/NavPose2DResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavPose2DResult>)))
  "Returns md5sum for a message object of type '<NavPose2DResult>"
  "80204a6ff2622a7071680d5597cbd3aa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavPose2DResult)))
  "Returns md5sum for a message object of type 'NavPose2DResult"
  "80204a6ff2622a7071680d5597cbd3aa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavPose2DResult>)))
  "Returns full string definition for message of type '<NavPose2DResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavPose2DResult)))
  "Returns full string definition for message of type 'NavPose2DResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavPose2DResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavPose2DResult>))
  "Converts a ROS message object to a list"
  (cl:list 'NavPose2DResult
    (cl:cons ':reached (reached msg))
))
