set(_CATKIN_CURRENT_PACKAGE "bullproof_hri")
set(bullproof_hri_VERSION "0.0.0")
set(bullproof_hri_MAINTAINER "jvandersaag <jvandersaag@todo.todo>")
set(bullproof_hri_PACKAGE_FORMAT "2")
set(bullproof_hri_BUILD_DEPENDS )
set(bullproof_hri_BUILD_EXPORT_DEPENDS )
set(bullproof_hri_BUILDTOOL_DEPENDS "catkin")
set(bullproof_hri_BUILDTOOL_EXPORT_DEPENDS )
set(bullproof_hri_EXEC_DEPENDS )
set(bullproof_hri_RUN_DEPENDS )
set(bullproof_hri_TEST_DEPENDS )
set(bullproof_hri_DOC_DEPENDS )
set(bullproof_hri_URL_WEBSITE "")
set(bullproof_hri_URL_BUGTRACKER "")
set(bullproof_hri_URL_REPOSITORY "")
set(bullproof_hri_DEPRECATED "")