// Auto-generated. Do not edit!

// (in-package bullproof_nav.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class NavPose2DFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.distance_left = null;
    }
    else {
      if (initObj.hasOwnProperty('distance_left')) {
        this.distance_left = initObj.distance_left
      }
      else {
        this.distance_left = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type NavPose2DFeedback
    // Serialize message field [distance_left]
    bufferOffset = _serializer.float32(obj.distance_left, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type NavPose2DFeedback
    let len;
    let data = new NavPose2DFeedback(null);
    // Deserialize message field [distance_left]
    data.distance_left = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'bullproof_nav/NavPose2DFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'cee420620fc0275f177e13260e85fa34';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float32 distance_left
    
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new NavPose2DFeedback(null);
    if (msg.distance_left !== undefined) {
      resolved.distance_left = msg.distance_left;
    }
    else {
      resolved.distance_left = 0.0
    }

    return resolved;
    }
};

module.exports = NavPose2DFeedback;
