mirte:
  # Settings for ros_control hardware interface
  hardware_interface:
     joints:
        - front_left_wheel_joint
        - front_right_wheel_joint
          
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    extra_joints:
      - name: rear_caster_rotation_joint
        position: 0.01
        velocity: 0.0
        effort: 0.0
      - name: rear_caster_wheel_joint
        position: 0.01
        velocity: 0.0
        effort: 0.0

  mobile_base_controller:
    type: diff_drive_controller/DiffDriveController
    publish_rate: 50

    left_wheel: 'front_left_wheel_joint'
    right_wheel: 'front_right_wheel_joint'

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.145
    wheel_radius : 0.0325

    # Odometry covariances for the encoder output of the robot. These values should
    # be tuned to your robot's sample odometry data, but these values are a good place
    # to start
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  
    # Top level frame (link) of the robot description
    base_frame_id: base_footprint

    # #Publish to TF directly or not
    enable_odom_tf: false

    # Velocity and acceleration limits for the robot
    linear:
      x:
        has_velocity_limits    : true
        #max_velocity           : 0.42 # m/s   at 5V
        max_velocity            : 0.55 # m/s   at 6V
  #      min_velocity           : -0.42 #-0.5 # m/s
        has_acceleration_limits: false
        #max_acceleration       : 0.42 #0.8  # m/s^2
        #min_acceleration       : -0.42 #-0.4 # m/s^2
        has_jerk_limits        : false
    #    max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2     #1.7  # rad/s
        has_acceleration_limits: false
        #max_acceleration       : 8  # rad/s^2
        has_jerk_limits        : false
        #max_jerk               : 2.5  # rad/s^3
