set(_CATKIN_CURRENT_PACKAGE "mirte_description")
set(mirte_description_VERSION "1.1.0")
set(mirte_description_MAINTAINER "nikhil <nikhil@todo.todo>")
set(mirte_description_PACKAGE_FORMAT "2")
set(mirte_description_BUILD_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz")
set(mirte_description_BUILD_EXPORT_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz")
set(mirte_description_BUILDTOOL_DEPENDS "catkin")
set(mirte_description_BUILDTOOL_EXPORT_DEPENDS )
set(mirte_description_EXEC_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz")
set(mirte_description_RUN_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz")
set(mirte_description_TEST_DEPENDS )
set(mirte_description_DOC_DEPENDS )
set(mirte_description_URL_WEBSITE "")
set(mirte_description_URL_BUGTRACKER "")
set(mirte_description_URL_REPOSITORY "")
set(mirte_description_DEPRECATED "")