standalone_tags:
  [
    {id: 0, size: 0.15},
    {id: 1, size: 0.1},
    {id: 2, size: 0.07},
    {id: 3, size: 0.07},
    {id: 4, size: 0.07},
    {id: 5, size: 0.07},
    {id: 6, size: 0.07},
    {id: 7, size: 0.07},
    {id: 8, size: 0.07},
    {id: 9, size: 0.07},
    {id: 10, size: 0.15},
    {id: 11, size: 0.1},
    {id: 12, size: 0.07},
    {id: 13, size: 0.07},
    {id: 14, size: 0.07},
    {id: 15, size: 0.07},
    {id: 16, size: 0.07},
    {id: 17, size: 0.07},
    {id: 18, size: 0.07},
    {id: 19, size: 0.07},
    {id: 20, size: 0.15},
    {id: 21, size: 0.1},
    {id: 22, size: 0.07},
    {id: 23, size: 0.07},
    {id: 24, size: 0.07},
    {id: 25, size: 0.07},
    {id: 26, size: 0.07},
    {id: 27, size: 0.07},
    {id: 28, size: 0.07},
    {id: 29, size: 0.07},
    {id: 30, size: 0.15},
    {id: 31, size: 0.1},
    {id: 32, size: 0.07},
    {id: 33, size: 0.07},
    {id: 34, size: 0.07},
    {id: 35, size: 0.07},
    {id: 36, size: 0.07},
    {id: 37, size: 0.07},
    {id: 38, size: 0.07},
    {id: 39, size: 0.07},
    {id: 40, size: 0.15},
    {id: 41, size: 0.1},
    {id: 42, size: 0.07},
    {id: 43, size: 0.07},
    {id: 44, size: 0.07},
    {id: 45, size: 0.07},
    {id: 46, size: 0.07},
    {id: 47, size: 0.07},
    {id: 48, size: 0.07},
    {id: 49, size: 0.07}    
  ]



# tag_bundles:
#   [
#     {
#       name: 'my_bundle',
#       layout:
#         [
#           {id: 0, size: 0.05, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#           {id: 4, size: 0.05, x: 0.0548, y: -0.0522, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#           {id: 3, size: 0.05, x: -0.0580, y: -0.0553, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#           {id: 2, size: 0.05, x: 0.0543, y: 0.0603, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#           {id: 1, size: 0.05, x: -0.0582, y: 0.0573, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
#         ]
#     }
#   ]