// Generated by gencpp from file bullproof_nav/NavPose2DGoal.msg
// DO NOT EDIT!


#ifndef BULLPROOF_NAV_MESSAGE_NAVPOSE2DGOAL_H
#define BULLPROOF_NAV_MESSAGE_NAVPOSE2DGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace bullproof_nav
{
template <class ContainerAllocator>
struct NavPose2DGoal_
{
  typedef NavPose2DGoal_<ContainerAllocator> Type;

  NavPose2DGoal_()
    : pose()  {
    }
  NavPose2DGoal_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavPose2DGoal_

typedef ::bullproof_nav::NavPose2DGoal_<std::allocator<void> > NavPose2DGoal;

typedef boost::shared_ptr< ::bullproof_nav::NavPose2DGoal > NavPose2DGoalPtr;
typedef boost::shared_ptr< ::bullproof_nav::NavPose2DGoal const> NavPose2DGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bullproof_nav::NavPose2DGoal_<ContainerAllocator1> & lhs, const ::bullproof_nav::NavPose2DGoal_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bullproof_nav::NavPose2DGoal_<ContainerAllocator1> & lhs, const ::bullproof_nav::NavPose2DGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bullproof_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "271cb12677c4cd9bccbc642cd9258d1f";
  }

  static const char* value(const ::bullproof_nav::NavPose2DGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x271cb12677c4cd9bULL;
  static const uint64_t static_value2 = 0xccbc642cd9258d1fULL;
};

template<class ContainerAllocator>
struct DataType< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bullproof_nav/NavPose2DGoal";
  }

  static const char* value(const ::bullproof_nav::NavPose2DGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/Pose2D pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::bullproof_nav::NavPose2DGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavPose2DGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bullproof_nav::NavPose2DGoal_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BULLPROOF_NAV_MESSAGE_NAVPOSE2DGOAL_H
