// Generated by gencpp from file bullproof_nav/NavPose2DActionGoal.msg
// DO NOT EDIT!


#ifndef BULLPROOF_NAV_MESSAGE_NAVPOSE2DACTIONGOAL_H
#define BULLPROOF_NAV_MESSAGE_NAVPOSE2DACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <bullproof_nav/NavPose2DGoal.h>

namespace bullproof_nav
{
template <class ContainerAllocator>
struct NavPose2DActionGoal_
{
  typedef NavPose2DActionGoal_<ContainerAllocator> Type;

  NavPose2DActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  NavPose2DActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::bullproof_nav::NavPose2DGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavPose2DActionGoal_

typedef ::bullproof_nav::NavPose2DActionGoal_<std::allocator<void> > NavPose2DActionGoal;

typedef boost::shared_ptr< ::bullproof_nav::NavPose2DActionGoal > NavPose2DActionGoalPtr;
typedef boost::shared_ptr< ::bullproof_nav::NavPose2DActionGoal const> NavPose2DActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator1> & lhs, const ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator1> & lhs, const ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bullproof_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "626de0c05bec91c35e2a87b1ef453a40";
  }

  static const char* value(const ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x626de0c05bec91c3ULL;
  static const uint64_t static_value2 = 0x5e2a87b1ef453a40ULL;
};

template<class ContainerAllocator>
struct DataType< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bullproof_nav/NavPose2DActionGoal";
  }

  static const char* value(const ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"NavPose2DGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: bullproof_nav/NavPose2DGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/Pose2D pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavPose2DActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bullproof_nav::NavPose2DActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::bullproof_nav::NavPose2DGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BULLPROOF_NAV_MESSAGE_NAVPOSE2DACTIONGOAL_H
