set(_CATKIN_CURRENT_PACKAGE "bullproof_perception")
set(bullproof_perception_VERSION "0.0.0")
set(bullproof_perception_MAINTAINER "jvandersaag <jvandersaag@todo.todo>")
set(bullproof_perception_PACKAGE_FORMAT "2")
set(bullproof_perception_BUILD_DEPENDS "map_server")
set(bullproof_perception_BUILD_EXPORT_DEPENDS "map_server")
set(bullproof_perception_BUILDTOOL_DEPENDS "catkin")
set(bullproof_perception_BUILDTOOL_EXPORT_DEPENDS )
set(bullproof_perception_EXEC_DEPENDS "map_server")
set(bullproof_perception_RUN_DEPENDS "map_server")
set(bullproof_perception_TEST_DEPENDS )
set(bullproof_perception_DOC_DEPENDS )
set(bullproof_perception_URL_WEBSITE "")
set(bullproof_perception_URL_BUGTRACKER "")
set(bullproof_perception_URL_REPOSITORY "")
set(bullproof_perception_DEPRECATED "")