set(_CATKIN_CURRENT_PACKAGE "bullproof_bringup")
set(bullproof_bringup_VERSION "0.0.0")
set(bullproof_bringup_MAINTAINER "nikhil <nikhil@todo.todo>")
set(bullproof_bringup_PACKAGE_FORMAT "2")
set(bullproof_bringup_BUILD_DEPENDS )
set(bullproof_bringup_BUILD_EXPORT_DEPENDS )
set(bullproof_bringup_BUILDTOOL_DEPENDS "catkin")
set(bullproof_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(bullproof_bringup_EXEC_DEPENDS )
set(bullproof_bringup_RUN_DEPENDS )
set(bullproof_bringup_TEST_DEPENDS )
set(bullproof_bringup_DOC_DEPENDS )
set(bullproof_bringup_URL_WEBSITE "")
set(bullproof_bringup_URL_BUGTRACKER "")
set(bullproof_bringup_URL_REPOSITORY "")
set(bullproof_bringup_DEPRECATED "")