set(_CATKIN_CURRENT_PACKAGE "mirte_sim")
set(mirte_sim_VERSION "0.0.0")
set(mirte_sim_MAINTAINER "nikhil <nikhil@todo.todo>")
set(mirte_sim_PACKAGE_FORMAT "2")
set(mirte_sim_BUILD_DEPENDS )
set(mirte_sim_BUILD_EXPORT_DEPENDS )
set(mirte_sim_BUILDTOOL_DEPENDS "catkin")
set(mirte_sim_BUILDTOOL_EXPORT_DEPENDS )
set(mirte_sim_EXEC_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "diffbot_control" "diffbot_description" "xacro")
set(mirte_sim_RUN_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "diffbot_control" "diffbot_description" "xacro")
set(mirte_sim_TEST_DEPENDS )
set(mirte_sim_DOC_DEPENDS )
set(mirte_sim_URL_WEBSITE "")
set(mirte_sim_URL_BUGTRACKER "")
set(mirte_sim_URL_REPOSITORY "")
set(mirte_sim_DEPRECATED "")